/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as ApiAdminAvailabilityRouteImport } from './routes/api/admin-availability'
import { Route as ApiAdminBookingsRouteImport } from './routes/api/admin-bookings'
import { Route as ApiAdminGalleryRouteImport } from './routes/api/admin-gallery'
import { Route as ApiAdminInquiriesRouteImport } from './routes/api/admin-inquiries'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin-login'
import { Route as ApiAdminLogoutRouteImport } from './routes/api/admin-logout'
import { Route as ApiAdminPaymentsRouteImport } from './routes/api/admin-payments'
import { Route as ApiBookingAvailabilityRouteImport } from './routes/api/booking-availability'
import { Route as ApiBookingPortalRouteImport } from './routes/api/booking-portal'
import { Route as ApiBookingSettingsRouteImport } from './routes/api/booking-settings'
import { Route as ApiBookingsRouteImport } from './routes/api/bookings'
import { Route as ApiGalleryRouteImport } from './routes/api/gallery'
import { Route as ApiInquiriesRouteImport } from './routes/api/inquiries'
import { Route as ApiPaymentBalanceRouteImport } from './routes/api/payment-balance'
import { Route as ApiPaymentMethodsRouteImport } from './routes/api/payment-methods'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe-webhook'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesSlugRouteImport } from './routes/services/$slug'
import { Route as WorkIndexRouteImport } from './routes/work/index'
import { Route as WorkSlugRouteImport } from './routes/work/$slug'
import { Route as ApiCalendarIdRouteImport } from './routes/api/calendar/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAvailabilityRoute = ApiAdminAvailabilityRouteImport.update({
  id: '/api/admin-availability',
  path: '/api/admin-availability',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBookingsRoute = ApiAdminBookingsRouteImport.update({
  id: '/api/admin-bookings',
  path: '/api/admin-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminGalleryRoute = ApiAdminGalleryRouteImport.update({
  id: '/api/admin-gallery',
  path: '/api/admin-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminInquiriesRoute = ApiAdminInquiriesRouteImport.update({
  id: '/api/admin-inquiries',
  path: '/api/admin-inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin-login',
  path: '/api/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin-logout',
  path: '/api/admin-logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPaymentsRoute = ApiAdminPaymentsRouteImport.update({
  id: '/api/admin-payments',
  path: '/api/admin-payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingAvailabilityRoute = ApiBookingAvailabilityRouteImport.update({
  id: '/api/booking-availability',
  path: '/api/booking-availability',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingPortalRoute = ApiBookingPortalRouteImport.update({
  id: '/api/booking-portal',
  path: '/api/booking-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingSettingsRoute = ApiBookingSettingsRouteImport.update({
  id: '/api/booking-settings',
  path: '/api/booking-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingsRoute = ApiBookingsRouteImport.update({
  id: '/api/bookings',
  path: '/api/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGalleryRoute = ApiGalleryRouteImport.update({
  id: '/api/gallery',
  path: '/api/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInquiriesRoute = ApiInquiriesRouteImport.update({
  id: '/api/inquiries',
  path: '/api/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentBalanceRoute = ApiPaymentBalanceRouteImport.update({
  id: '/api/payment-balance',
  path: '/api/payment-balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentMethodsRoute = ApiPaymentMethodsRouteImport.update({
  id: '/api/payment-methods',
  path: '/api/payment-methods',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarIdRoute = ApiCalendarIdRouteImport.update({
  id: '/api/calendar/$id',
  path: '/api/calendar/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/api/admin-availability': typeof ApiAdminAvailabilityRoute
  '/api/admin-bookings': typeof ApiAdminBookingsRoute
  '/api/admin-gallery': typeof ApiAdminGalleryRoute
  '/api/admin-inquiries': typeof ApiAdminInquiriesRoute
  '/api/admin-login': typeof ApiAdminLoginRoute
  '/api/admin-logout': typeof ApiAdminLogoutRoute
  '/api/admin-payments': typeof ApiAdminPaymentsRoute
  '/api/booking-availability': typeof ApiBookingAvailabilityRoute
  '/api/booking-portal': typeof ApiBookingPortalRoute
  '/api/booking-settings': typeof ApiBookingSettingsRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/api/gallery': typeof ApiGalleryRoute
  '/api/inquiries': typeof ApiInquiriesRoute
  '/api/payment-balance': typeof ApiPaymentBalanceRoute
  '/api/payment-methods': typeof ApiPaymentMethodsRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/services/': typeof ServicesIndexRoute
  '/work/': typeof WorkIndexRoute
  '/api/calendar/$id': typeof ApiCalendarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/api/admin-availability': typeof ApiAdminAvailabilityRoute
  '/api/admin-bookings': typeof ApiAdminBookingsRoute
  '/api/admin-gallery': typeof ApiAdminGalleryRoute
  '/api/admin-inquiries': typeof ApiAdminInquiriesRoute
  '/api/admin-login': typeof ApiAdminLoginRoute
  '/api/admin-logout': typeof ApiAdminLogoutRoute
  '/api/admin-payments': typeof ApiAdminPaymentsRoute
  '/api/booking-availability': typeof ApiBookingAvailabilityRoute
  '/api/booking-portal': typeof ApiBookingPortalRoute
  '/api/booking-settings': typeof ApiBookingSettingsRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/api/gallery': typeof ApiGalleryRoute
  '/api/inquiries': typeof ApiInquiriesRoute
  '/api/payment-balance': typeof ApiPaymentBalanceRoute
  '/api/payment-methods': typeof ApiPaymentMethodsRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/services': typeof ServicesIndexRoute
  '/work': typeof WorkIndexRoute
  '/api/calendar/$id': typeof ApiCalendarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/api/admin-availability': typeof ApiAdminAvailabilityRoute
  '/api/admin-bookings': typeof ApiAdminBookingsRoute
  '/api/admin-gallery': typeof ApiAdminGalleryRoute
  '/api/admin-inquiries': typeof ApiAdminInquiriesRoute
  '/api/admin-login': typeof ApiAdminLoginRoute
  '/api/admin-logout': typeof ApiAdminLogoutRoute
  '/api/admin-payments': typeof ApiAdminPaymentsRoute
  '/api/booking-availability': typeof ApiBookingAvailabilityRoute
  '/api/booking-portal': typeof ApiBookingPortalRoute
  '/api/booking-settings': typeof ApiBookingSettingsRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/api/gallery': typeof ApiGalleryRoute
  '/api/inquiries': typeof ApiInquiriesRoute
  '/api/payment-balance': typeof ApiPaymentBalanceRoute
  '/api/payment-methods': typeof ApiPaymentMethodsRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/services/': typeof ServicesIndexRoute
  '/work/': typeof WorkIndexRoute
  '/api/calendar/$id': typeof ApiCalendarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/admin'
    | '/booking'
    | '/contact'
    | '/experience'
    | '/api/admin-availability'
    | '/api/admin-bookings'
    | '/api/admin-gallery'
    | '/api/admin-inquiries'
    | '/api/admin-login'
    | '/api/admin-logout'
    | '/api/admin-payments'
    | '/api/booking-availability'
    | '/api/booking-portal'
    | '/api/booking-settings'
    | '/api/bookings'
    | '/api/gallery'
    | '/api/inquiries'
    | '/api/payment-balance'
    | '/api/payment-methods'
    | '/api/stripe-webhook'
    | '/services/$slug'
    | '/work/$slug'
    | '/services/'
    | '/work/'
    | '/api/calendar/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/admin'
    | '/booking'
    | '/contact'
    | '/experience'
    | '/api/admin-availability'
    | '/api/admin-bookings'
    | '/api/admin-gallery'
    | '/api/admin-inquiries'
    | '/api/admin-login'
    | '/api/admin-logout'
    | '/api/admin-payments'
    | '/api/booking-availability'
    | '/api/booking-portal'
    | '/api/booking-settings'
    | '/api/bookings'
    | '/api/gallery'
    | '/api/inquiries'
    | '/api/payment-balance'
    | '/api/payment-methods'
    | '/api/stripe-webhook'
    | '/services/$slug'
    | '/work/$slug'
    | '/services'
    | '/work'
    | '/api/calendar/$id'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/admin'
    | '/booking'
    | '/contact'
    | '/experience'
    | '/api/admin-availability'
    | '/api/admin-bookings'
    | '/api/admin-gallery'
    | '/api/admin-inquiries'
    | '/api/admin-login'
    | '/api/admin-logout'
    | '/api/admin-payments'
    | '/api/booking-availability'
    | '/api/booking-portal'
    | '/api/booking-settings'
    | '/api/bookings'
    | '/api/gallery'
    | '/api/inquiries'
    | '/api/payment-balance'
    | '/api/payment-methods'
    | '/api/stripe-webhook'
    | '/services/$slug'
    | '/work/$slug'
    | '/services/'
    | '/work/'
    | '/api/calendar/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BookingRoute: typeof BookingRoute
  ContactRoute: typeof ContactRoute
  ExperienceRoute: typeof ExperienceRoute
  ApiAdminAvailabilityRoute: typeof ApiAdminAvailabilityRoute
  ApiAdminBookingsRoute: typeof ApiAdminBookingsRoute
  ApiAdminGalleryRoute: typeof ApiAdminGalleryRoute
  ApiAdminInquiriesRoute: typeof ApiAdminInquiriesRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminPaymentsRoute: typeof ApiAdminPaymentsRoute
  ApiBookingAvailabilityRoute: typeof ApiBookingAvailabilityRoute
  ApiBookingPortalRoute: typeof ApiBookingPortalRoute
  ApiBookingSettingsRoute: typeof ApiBookingSettingsRoute
  ApiBookingsRoute: typeof ApiBookingsRoute
  ApiGalleryRoute: typeof ApiGalleryRoute
  ApiInquiriesRoute: typeof ApiInquiriesRoute
  ApiPaymentBalanceRoute: typeof ApiPaymentBalanceRoute
  ApiPaymentMethodsRoute: typeof ApiPaymentMethodsRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  WorkSlugRoute: typeof WorkSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  WorkIndexRoute: typeof WorkIndexRoute
  ApiCalendarIdRoute: typeof ApiCalendarIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-availability': {
      id: '/api/admin-availability'
      path: '/api/admin-availability'
      fullPath: '/api/admin-availability'
      preLoaderRoute: typeof ApiAdminAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-bookings': {
      id: '/api/admin-bookings'
      path: '/api/admin-bookings'
      fullPath: '/api/admin-bookings'
      preLoaderRoute: typeof ApiAdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-gallery': {
      id: '/api/admin-gallery'
      path: '/api/admin-gallery'
      fullPath: '/api/admin-gallery'
      preLoaderRoute: typeof ApiAdminGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-inquiries': {
      id: '/api/admin-inquiries'
      path: '/api/admin-inquiries'
      fullPath: '/api/admin-inquiries'
      preLoaderRoute: typeof ApiAdminInquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-login': {
      id: '/api/admin-login'
      path: '/api/admin-login'
      fullPath: '/api/admin-login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-logout': {
      id: '/api/admin-logout'
      path: '/api/admin-logout'
      fullPath: '/api/admin-logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-payments': {
      id: '/api/admin-payments'
      path: '/api/admin-payments'
      fullPath: '/api/admin-payments'
      preLoaderRoute: typeof ApiAdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/booking-availability': {
      id: '/api/booking-availability'
      path: '/api/booking-availability'
      fullPath: '/api/booking-availability'
      preLoaderRoute: typeof ApiBookingAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/booking-portal': {
      id: '/api/booking-portal'
      path: '/api/booking-portal'
      fullPath: '/api/booking-portal'
      preLoaderRoute: typeof ApiBookingPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/booking-settings': {
      id: '/api/booking-settings'
      path: '/api/booking-settings'
      fullPath: '/api/booking-settings'
      preLoaderRoute: typeof ApiBookingSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookings': {
      id: '/api/bookings'
      path: '/api/bookings'
      fullPath: '/api/bookings'
      preLoaderRoute: typeof ApiBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gallery': {
      id: '/api/gallery'
      path: '/api/gallery'
      fullPath: '/api/gallery'
      preLoaderRoute: typeof ApiGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inquiries': {
      id: '/api/inquiries'
      path: '/api/inquiries'
      fullPath: '/api/inquiries'
      preLoaderRoute: typeof ApiInquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment-balance': {
      id: '/api/payment-balance'
      path: '/api/payment-balance'
      fullPath: '/api/payment-balance'
      preLoaderRoute: typeof ApiPaymentBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment-methods': {
      id: '/api/payment-methods'
      path: '/api/payment-methods'
      fullPath: '/api/payment-methods'
      preLoaderRoute: typeof ApiPaymentMethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar/$id': {
      id: '/api/calendar/$id'
      path: '/api/calendar/$id'
      fullPath: '/api/calendar/$id'
      preLoaderRoute: typeof ApiCalendarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BookingRoute: BookingRoute,
  ContactRoute: ContactRoute,
  ExperienceRoute: ExperienceRoute,
  ApiAdminAvailabilityRoute: ApiAdminAvailabilityRoute,
  ApiAdminBookingsRoute: ApiAdminBookingsRoute,
  ApiAdminGalleryRoute: ApiAdminGalleryRoute,
  ApiAdminInquiriesRoute: ApiAdminInquiriesRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminPaymentsRoute: ApiAdminPaymentsRoute,
  ApiBookingAvailabilityRoute: ApiBookingAvailabilityRoute,
  ApiBookingPortalRoute: ApiBookingPortalRoute,
  ApiBookingSettingsRoute: ApiBookingSettingsRoute,
  ApiBookingsRoute: ApiBookingsRoute,
  ApiGalleryRoute: ApiGalleryRoute,
  ApiInquiriesRoute: ApiInquiriesRoute,
  ApiPaymentBalanceRoute: ApiPaymentBalanceRoute,
  ApiPaymentMethodsRoute: ApiPaymentMethodsRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  WorkSlugRoute: WorkSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  WorkIndexRoute: WorkIndexRoute,
  ApiCalendarIdRoute: ApiCalendarIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
